[config.wallpaper]
set = true
command = "swww"
arguments = ["img", "--transition-type", "wave"]

[templates.hyprland]
input_path = './templates/hyprland-colors.conf'
output_path = '~/.config/matugen/output/hyprland_colors.conf'
post_hook = 'hyprctl reload config-only -q'

[templates.niri]
input_path = './templates/niri-colors.kdl'
output_path = '~/.config/matugen/output/niri_colors.kdl'
post_hook = 'niri msg action load-config-file'

[templates.waybar]
input_path = './templates/colors.conf'
output_path = '~/.config/matugen/output/waybar_colors.css'
post_hook = 'pkill -SIGUSR2 waybar & pkill -SIGUSR2 swaync'

[templates.kitty]
input_path = './templates/kitty-colors.conf'
output_path = '~/.config/matugen/output/kitty_colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'

[templates.alacritty]
input_path = './templates/alacritty.toml'
output_path = '~/.config/matugen/output/alacritty_colors.toml'

[templates.sway]
input_path = './templates/sway-colors.conf'
output_path = '~/.config/matugen/output/sway_colors.conf'

[templates.rofi]
input_path = './templates/rofi.rasi'
output_path = '~/.config/matugen/output/rofi_colors.rasi'

[templates.btop]
input_path = './templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'

###############################################################

[templates.gtk3]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme Adwaita-{{mode}}'
